### ISSUE TITLE
logo/icon

### ISSUE THREAD

**Issue by hafizahmmed** [VidBregar/Baking-App#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![baking-app-01](https://user-images.githubusercontent.com/38810169/39400057-bc4ce0d2-4b4a-11e8-8254-ee5feedb2704.jpg)

thankyou

**Comment by VidBregar** [comment]
Hi,
Thank you for your recommendation. I have been thinking about adding the logo as well, but I haven't managed to create one yet.
I think it looks nice! Feel free to add it to my project, but please make sure it supports adaptive icons since I am targeting the latest API.
More on adaptive icons ([link](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive?authuser=3))

**Comment by hafizahmmed** [comment]
![baking-app icon-01](https://user-images.githubusercontent.com/38810169/39438505-3b55e8ca-4cc6-11e8-9bc2-278a7451cd06.jpg)


https://drive.google.com/open?id=1bZR-yp4Pitbppg1fbOaDKRFTYFk3nkJQ

**Comment by VidBregar** [comment]
Hey,
could you please make the background of the logo in teal color (hex: #008975)
Thank you!

**Comment by hafizahmmed** [comment]
![baking-app icon-01-01](https://user-images.githubusercontent.com/38810169/39439584-eb632464-4cc9-11e8-9792-fb8a7ad3f5d7.jpg)

**Comment by VidBregar** [comment]
Thanks, I will add your logo to my project soon.

**Comment by hafizahmmed** [comment]
thank you 

sir when you add this ??

**Comment by VidBregar** [comment]
Launcher icon updated
See commit 449eba99425c9d46ada881f89fcd6c649926f0b4
